---

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages: "{{ lookup('file', '../files/apt').splitlines() }}"
- name: Add or modify nofile soft and hard limits for all users
  community.general.pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nofile
    value: 100000
- name: Add or modify nofile soft and hard limits for all users
  community.general.pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: nproc
    value: 100000
- name: Download Datafari
  ansible.builtin.get_url:
    url: https://www.datafari.com/files/debian/datafari_{{ datafari_version }}.deb
    dest: /{{ datafari_download_dir }}/datafari_{{ datafari_version }}.deb
    mode: '0755'

- name: Install deb
  ansible.builtin.apt:
    deb: /{{ datafari_download_dir }}/datafari_{{ datafari_version }}.deb

- name: Manage datafari properties file template
  ansible.builtin.template:
    src: datafari.properties.j2
    dest: /opt/datafari/tomcat/conf/datafari.properties
    mode: '0755'
    owner: datafari

- name: Get variable init_state properties
  ansible.builtin.shell: cat /opt/datafari/bin/common/init_state.properties
  register: init_state

- name: Init Datafari
  ansible.builtin.shell:
  changed_when: false
  args:
    cmd: bash -c ". /etc/profile && ./init-datafari.sh > /opt/datafari/logs/init-datafari.txt"
    chdir: /opt/datafari/bin
  when: init_state.stdout.find('active') == -1


- name: Getting process IDs of the Datafari Tomcat processes
  community.general.pids:
      pattern: .*tomcat.*
  register: pids_of_datafari

- name: Start Datafari
  ansible.builtin.shell:
  changed_when: false
  args:
    cmd: bash -c ". /etc/profile && ./start-datafari.sh > /opt/datafari/logs/start-datafari.txt"
    chdir: /opt/datafari/bin
  when: pids_of_datafari == ""
